import os
import time


def animacaoJogoDaVelha(tempo, vezes):
    def freme(tempo):
        time.sleep(tempo)
        print('\n' * 40)
    i = 0
    while i  < vezes: 
        freme(tempo)  
        print('*')
        freme(tempo)
        print('**')
        freme(tempo)
        print('***')
        freme(tempo)
        
        print('****')
        freme(tempo)
        
        print('*****')
        freme(tempo)
        print('A*****')
        freme(tempo)
        print('HA*****')
        freme(tempo)
        print('LHA*****')
        freme(tempo)
        print('ELHA*****')
        freme(tempo)
        print('VELHA*****')
        freme(tempo)
        print(' VELHA*****')
        freme(tempo)
        print('A VELHA*****')
        freme(tempo)
        print('DA VELHA*****')
        freme(tempo)
        print(' DA VELHA*****')
        freme(tempo)        
        print('O DA VELHA*****')
        freme(tempo)
        print('GO DA VELHA*****')
        freme(tempo)
        print('OGO DA VELHA*****')
        freme(tempo)
        print('*JOGO DA VELHA*****')
        freme(tempo)
        print('**JOGO DA VELHA*****')
        freme(tempo)
        print('***JOGO DA VELHA*****')
        freme(tempo)
        print('****JOGO DA VELHA*****')
        freme(tempo)
        print('*****JOGO DA VELHA*****')
        freme(tempo)
        print(' *****JOGO DA VELHA*****')
        freme(tempo)
        print('  *****JOGO DA VELHA*****')
        freme(tempo)
        print('   *****JOGO DA VELHA*****')
        freme(tempo)
        print('    *****JOGO DA VELHA*****')
        freme(tempo)
        print('     *****JOGO DA VELHA*****')
        freme(tempo)
        print('      *****JOGO DA VELHA*****')
        freme(tempo)
        print('       *****JOGO DA VELHA*****')
        freme(tempo)
        print('        *****JOGO DA VELHA*****')
        freme(tempo)
        print('         *****JOGO DA VELHA*****')
        freme(tempo)
        print('          *****JOGO DA VELHA*****')
        freme(tempo)
        print('           *****JOGO DA VELHA*****')
        freme(tempo)
        print('            *****JOGO DA VELHA*****')
        freme(tempo)
        print('             *****JOGO DA VELHA*****')
        
        i = i + 1
    time.sleep(1.0)
    
animacaoJogoDaVelha(0.05, 3)
